from typing import Protocol, List, runtime_checkable
import logging

@runtime_checkable
class Registrador(Protocol):
    def informar(self, msg: str) -> None: ...
    def registrar_error(self, msg: str, exc_info: bool = False) -> None: ...
    def depurar(self, msg: str) -> None: ...
    def advertir(self, msg: str) -> None: ...
